import Head from "next/head";
import Hero from "../components/hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[url('/assets/img/background.png')] bg-cover bg-top">
        <Hero />
      </main>
    </>
  );
}
